services:
- type: web
  name: career-forge-backend
    plan: free
      env: node
        rootDir: Backend
          buildCommand: npm install
            startCommand: node server.js
              envVars:
                - key: MONGO_URI
                    sync: false
                      - key: JWT_SECRET
                          sync: false
                            - key: GROQ_API_KEY
                                sync: false
                                  - key: FRONTEND_URL
                                      fromService:
                                            type: static
                                                  name: career-forge-frontend
                                                        envVarKey: RENDER_EXTERNAL_URL
                                                        - type: static
                                                          name: career-forge-frontend
                                                            env: static
                                                              rootDir: Frontend
                                                                buildCommand: npm install && npm run build
                                                                  staticPublishDir: dist
